In [1]:
# !git clone https://trongtuyen99:password@github.com/trongtuyen99/20news_goup_data.git
!git clone https://github.com/trongtuyen99/20news_goup_data.git

Cloning into '20news_goup_data'...
remote: Enumerating objects: 37708, done.
remote: Counting objects: 100% (37708/37708), done.
remote: Compressing objects: 100% (37638/37638), done.
remote: Total 37708 (delta 67), reused 37699 (delta 64), pack-reused 0
Receiving objects: 100% (37708/37708), 30.21 MiB | 21.92 MiB/s, done.
Resolving deltas: 100% (67/67), done.
Checking out files: 100% (37622/37622), done.


# import required lib

In [2]:
import os
import re
import nltk
import joblib
import numpy as np
from collections import Counter, defaultdict

from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression as LR

from gensim.utils import simple_preprocess

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer
nltk.download('wordnet') # for steemmerize
nltk.download('stopwords') # for remove stops word

import torch
from torch.autograd import Variable
from torch.utils.data import Dataset, DataLoader
from torchsummary import summary
from time import time

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [3]:
class Prepro():
    """using framework"""
    def __init__(self, min_df):
        self.stop_words = stopwords.words("english")
        self.min_df = min_df
        self.stemmer = PorterStemmer()

    def remove_stop_words(self, text):
        for word in self.stop_words:
                text = text.replace(" "+word+" ", " ")
        return text

    def get_words(self, text):
        return simple_preprocess(text)

    def stem(self, word):
      return self.stemmer.stem(word)

    def create_dict_from_array(self, doc): # not using
      """doc: list of list word"""
      dict_corpus = defaultdict(int)
      for d in doc:
          for w in d:
              dict_corpus[w] += 1
      return dict_corpus
    
    def get_data_from_dir(self, path):
        "return list of doc "
        all_files = []
        data = []
        for root, dirs, files in os.walk(path, topdown=True):
            for name in files:
                all_files.append(os.path.join(root, name))
    
        for file in all_files:
          with open(file, 'r') as reader:
            try:
              text = reader.read()
              data.append(text)
            except:
              pass
        return data

    def process(self, sentence):
      text = self.remove_stop_words(sentence)
      list_words = self.get_words(text)
      word_stem = [my_prepro.stem(w) for w in list_words]
      result = " ".join(word_stem)
    
    def save_serialize(obj, file_path):
      joblib.dump(obj, file_path)

    def create_word_freq(self, list_text):
      """ list text: list of paragraph"""
      word_freq = defaultdict(int) 
      word_doc_freq = defaultdict(int)
      n = len(list_text)
      for s in list_text:
        words = s.split()
        for word in words:
          word_freq[word] += 1
        set_words = set(words)
        for word in set_words:
          word_doc_freq[word] += 1
      for k in word_doc_freq.keys():
        word_doc_freq[k] /= n
      return word_freq, word_doc_freq

# remove stopword, special, redundant sign/space, stemmer

In [ ]:
# preprocess data and save
my_prepro = Prepro(4)
SAVE_DIR = r"data/20news-bydate-train-preprocess"
PATH = r"data/20news-bydate-train"

# SAVE_DIR = r"data/20news-bydate-test-preprocess"
# PATH = r"data/20news-bydate-test"
for d in os.listdir(PATH):
  print(d)
  try:
    os.mkdir(os.path.join(SAVE_DIR, d))
  except:
    # pass
    continue
  directory = os.path.join(PATH, d)
  for file in os.listdir(directory):
    try:
      # print(file)
      my_file = os.path.join(directory, file)
      data = open(my_file, "r").read()
      text = my_prepro.remove_stop_words(data)
      list_words = my_prepro.get_words(text)
      word_stem = [my_prepro.stem(w) for w in list_words]
      result = " ".join(word_stem)
      save_file = os.path.join(SAVE_DIR, d, file)
      with open(save_file, "w") as save:
        save.write(result)
    except:
      pass

1. create word freq dict from dir => for remove unusual word
2. create word-doc freq for tfidf
 

In [ ]:
my_prepro = Prepro(4)
data_test = my_prepro.get_data_from_dir(r'/content/20news_goup_data/data/20news-bydate-test-preprocess')
data_train = my_prepro.get_data_from_dir(r'/content/20news_goup_data/data/20news-bydate-train-preprocess')
# all_data = data_test + data_train
word_freq, word_doc_freq = my_prepro.create_word_freq(data_train)

In [ ]:
word_freq = sorted(word_freq.items(), key=lambda x: x[1])
word_doc_freq = sorted(word_doc_freq.items(), key=lambda x: x[1])

[('the', 0.6968944099378882),
 ('organ', 0.9627329192546584),
 ('line', 0.9971606033717835),
 ('subject', 1.0),
 ('from', 1.0)]

In [ ]:
joblib.dump(word_freq, "word_freq_train") # list
joblib.dump(word_doc_freq, "word_doc_freq_train") #list

['word_doc_freq_train']

# CounterVecorize, TfIdfVectorize

In [ ]:
%cd /content/20news_goup_data/data

/content/20news_goup_data/data


In [ ]:
!ls

20news-bydate-test	       20news-bydate-train-preprocess  word_freq_train
20news-bydate-test-preprocess  README.MD
20news-bydate-train	       word_doc_freq_train


In [ ]:
class CounterVectorize():
  def __init__(self, path_word_freq, df):
    self.word_freq = joblib.load(path_word_freq)
    self.df = df # for using word that freq > df
    all_words = list(filter(lambda x: x[1]>df, self.word_freq))
    self.all_words = list(dict(all_words).keys())
  def vectorize(self, sentence):
    words = sentence.split()
    n = len(self.all_words) + 1
    vector = [0] * n
    for w in words:
      flag = False
      for i, w2 in enumerate(self.all_words):
        if w == w2:
          vector[i] += 1
          flag = True
      if not flag:
        vector[n-1] += 1 # word not exist in all_words
    return vector
  def count_vectorize(self, list_text):
    rs = []
    for s in list_text:
      rs.append(vectorize(s))
    return rs



In [ ]:
c = CounterVectorize('word_freq_train', 3)
print(c.vectorize('dog eat meat'))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [ ]:
class TfIdfVectorize():
  def __init__(self, path_word_doc_freq, path_word_freq, df):
    self.df = df
    word_doc_freq = joblib.load(path_word_doc_freq)
    self.word_doc_freq = dict(word_doc_freq)

    self.word_freq = joblib.load(path_word_freq)
    all_words = list(filter(lambda x: x[1]>df, self.word_freq))
    self.all_words = list(dict(all_words).keys())
  def vectorize(self, sentence):
    words = sentence.split()
    n = len(self.all_words) + 1
    vector = [0] * n
    def tf(words):
      n = len(words)
      w_freq = Counter(words) # vectorize here is ok
      for k in w_freq.keys():
        w_freq[k] /= n
      return w_freq 
    def idf(words):
      import math
      n = len(words)
      rs = defaultdict()
      for w in words:
        r = self.word_doc_freq.get(w, 1)
        rs[w] = math.log(1/r) # inverse doc freq
      return rs

    tf_ = tf(words)
    idf_ = idf(words)
    for w in words:
      tf_idf = tf_[w] * idf_[w]
      flag = False
      for i, w2 in enumerate(self.all_words):
        if w == w2:
          vector[i] += tf_idf
          flag = True
      if not flag:
        vector[n-1] += 1 # word not exist in all_words
    return vector

  def tfidf_vectorize(self, list_text):
    rs = []
    for sentence in list_text:
      pass


In [ ]:
t = TfIdfVectorize("word_doc_freq_train", "word_freq_train", 3)
v = t.vectorize("my horse in here")

25008
0.5515567054573037
25096
0.44467818493441813
25190
0.12211284073374086
25194
1


# CountVectorize + TFIDF SAVE DATA

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
%cd /content/20news_goup_data/data
# PATH_TRAIN = r"/content/20news_goup_data/data/20news-bydate-train-preprocess"
PATH_TRAIN = r"/content/20news_goup_data/data/20news-bydate-test-preprocess"
class_name = os.listdir(PATH_TRAIN)
X = []
Y = []
prepro = Prepro(3)
vectorize = CounterVectorize('word_freq_train', 3)
i = 0
for c in class_name:
  path =  os.path.join(PATH_TRAIN, c)
  data = prepro.get_data_from_dir(path)
  size = len(data)
  Y += [c] * size
  print("class {}: \n".format(c))
  for d in data:
    i += 1
    X.append(vectorize.vectorize(d))
  print("done: {}".format(i/18888))
print("done!.........")
print(Y[:10])
print(X[:10])


##### Raw text

In [4]:

%cd /content/20news_goup_data/data
PATH_TRAIN = r"/content/20news_goup_data/data/20news-bydate-train-preprocess"
PATH_TEST = r"/content/20news_goup_data/data/20news-bydate-test-preprocess"

class_name = os.listdir(PATH_TRAIN)

X_train = []
Y_train = []
prepro = Prepro(5)
i = 0
for c in class_name:
  path =  os.path.join(PATH_TRAIN, c)
  data = prepro.get_data_from_dir(path)
  size = len(data)
  Y_train += [c] * size
  for d in data:
    i+= 1
    X_train.append(d)

# train data
class_name = os.listdir(PATH_TEST)

X_test = []
Y_test = []
prepro = Prepro(5)
i = 0
for c in class_name:
  path =  os.path.join(PATH_TEST, c)
  data = prepro.get_data_from_dir(path)
  size = len(data)
  Y_test += [c] * size
  for d in data:
    i+= 1
    X_test.append(d)


from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(Y_train)
Y_train = le.transform(Y_train)
Y_test = le.transform(Y_test)

X_train, Y_train, X_test, Y_test = np.array(X_train), np.array(Y_train), np.array(X_test), np.array(Y_test)

/content/20news_goup_data/data


In [ ]:
# using origin 
from gensim.utils import simple_preprocess
%cd /content/20news_goup_data/data
PATH_TRAIN = r"/content/20news_goup_data/data/20news-bydate-train"
PATH_TEST = r"/content/20news_goup_data/data/20news-bydate-test"

class_name = os.listdir(PATH_TRAIN)

X_train_origin = []
Y_train_origin = []
prepro = Prepro(5)
i = 0
for c in class_name:
  path =  os.path.join(PATH_TRAIN, c)
  data = prepro.get_data_from_dir(path)
  size = len(data)
  Y_train_origin += [c] * size
  for d in data:
    i+= 1
    X_train_origin.append(simple_preprocess(d))

# train data
class_name = os.listdir(PATH_TEST)

X_test_origin = []
Y_test_origin = []
prepro = Prepro(5)
i = 0
for c in class_name:
  path =  os.path.join(PATH_TEST, c)
  data = prepro.get_data_from_dir(path)
  size = len(data)
  Y_test_origin += [c] * size
  for d in data:
    i+= 1
    X_test_origin.append(simple_preprocess(d))


from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(Y_train_origin)
Y_train_origin = le.transform(Y_train_origin)
Y_test = le.transform(Y_test_origin)

X_train_origin, Y_train_origin, X_test_origin, Y_test_origin = np.array(X_train_origin), np.array(Y_train_origin), np.array(X_test_origin), np.array(Y_test_origin)

##### Count vectorize

In [ ]:
# Count vectorize

from sklearn.feature_extraction.text import CountVectorizer
%cd /content/20news_goup_data/data
PATH_TRAIN = r"/content/20news_goup_data/data/20news-bydate-train-preprocess"
PATH_TEST = r"/content/20news_goup_data/data/20news-bydate-test-preprocess"

class_name = os.listdir(PATH_TRAIN)

X_train_count = []
Y_train_count = []
prepro = Prepro(5)
i = 0
for c in class_name:
  path =  os.path.join(PATH_TRAIN, c)
  data = prepro.get_data_from_dir(path)
  size = len(data)
  Y_train_count += [c] * size
  for d in data:
    i+= 1
    X_train_count.append(d)

# train data
class_name = os.listdir(PATH_TEST)

X_test_count = []
Y_test_count = []
prepro = Prepro(5)
i = 0
for c in class_name:
  path =  os.path.join(PATH_TEST, c)
  data = prepro.get_data_from_dir(path)
  size = len(data)
  Y_test_count += [c] * size
  for d in data:
    i+= 1
    X_test_count.append(d)

vectorize = CountVectorizer(min_df=5)
vectorize.fit(X_train_count)
X_train_count = vectorize.transform(X_train_count)
X_test_count = vectorize.transform(X_test_count)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(Y_train_count)
Y_train_transform = le.transform(Y_train_count)
Y_test_transform = le.transform(Y_test_count)

/content/20news_goup_data/data


In [ ]:
X_train_count_idx = [] 
for i in range(X_train_count.shape[0]):
    X_train_count_idx.append(list(np.where(X_train_count[i].toarray() == 1)[1])) # 2d input, not 1d

X_test_count_idx = [] 
for i in range(X_test_count.shape[0]):
    X_test_count_idx.append(list(np.where(X_test_count[i].toarray() == 1)[1])) # 2d input, not 1d

In [ ]:
len(X_train_count_idx)

11270

In [ ]:
X_train_count_idx = np.array(X_train_count_idx)
X_train_count_idx.shape

(11270, 2)

--------------------------------

In [ ]:
# TF IDF vectorize

from sklearn.feature_extraction.text import TfidfVectorizer
%cd /content/20news_goup_data/data
PATH_TRAIN = r"/content/20news_goup_data/data/20news-bydate-train-preprocess"
# PATH_TRAIN = r"/content/20news_goup_data/data/20news-bydate-test-preprocess"
class_name = os.listdir(PATH_TRAIN)

X_train_tfidf = []
Y_train_tfidf = []
prepro = Prepro(3)
i = 0
for c in class_name:
  path =  os.path.join(PATH_TRAIN, c)
  data = prepro.get_data_from_dir(path)
  size = len(data)
  Y_train_tfidf += [c] * size
  # print("class {}: \n".format(c))
  for d in data:
    i+= 1
    X_train_tfidf.append(d)
  # print("done: {}".format(i/18888))


/content/20news_goup_data/data


In [ ]:
# TF IDF vectorize

from sklearn.feature_extraction.text import TfidfVectorizer
%cd /content/20news_goup_data/data
# PATH_TRAIN = r"/content/20news_goup_data/data/20news-bydate-train-preprocess"
PATH_TEST = r"/content/20news_goup_data/data/20news-bydate-test-preprocess"
class_name = os.listdir(PATH_TEST)

X_test_tfidf = []
Y_test_tfidf = []
prepro = Prepro(3)
i = 0
for c in class_name:
  path =  os.path.join(PATH_TEST, c)
  data = prepro.get_data_from_dir(path)
  size = len(data)
  Y_test_tfidf += [c] * size
  # print("class {}: \n".format(c))
  for d in data:
    i+= 1
    X_test_tfidf.append(d)
  # print("done: {}".format(i/18888))


/content/20news_goup_data/data


In [ ]:
vectorize_tfidf = TfidfVectorizer(min_df=3)
vectorize_tfidf.fit(X_train_tfidf)
X_train_tfidf = vectorize_tfidf.transform(X_train_tfidf)
X_test_tfidf = vectorize_tfidf.transform(X_test_tfidf)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(Y_train_tfidf)
Y_train_transform = le.transform(Y_train_tfidf)
Y_test_transform = le.transform(Y_test_tfidf)

In [ ]:
X_train_tfidf.shape

(11270, 24888)

In [ ]:
%cd /content/drive/My Drive
# !git status
joblib.dump(X_test_tfidf, "X_tfidf_test.lfs")
joblib.dump(Y_train_tfidf, "Y_tfidf_test")


/content/drive/My Drive


['Y_tfidf_test']

In [ ]:
!sudo apt-get install git-lfs

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  git-lfs
0 upgraded, 1 newly installed, 0 to remove and 25 not upgraded.
Need to get 2,129 kB of archives.
After this operation, 7,662 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 git-lfs amd64 2.3.4-1 [2,129 kB]
Fetched 2,129 kB in 1s (2,556 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Selecting previously unselected package git-lfs.
(Reading database ... 144568 files and directories c

# Load train and test data

In [ ]:
X_train = joblib.load("/content/drive/My Drive/X_tfidf_train.lfs")
Y_train= joblib.load("/content/drive/My Drive/Y_tfidf_train")
X_train = np.asarray(X_train)
Y_train = np.asarray(Y_train)

X_test = joblib.load("/content/drive/My Drive/X_tfidf_test.lfs")
Y_test= joblib.load("/content/drive/My Drive/Y_tfidf_test")
X_test = np.asarray(X_test)
Y_test = np.asarray(Y_test)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(Y_train)
Y_train_transform = le.transform(Y_train)
Y_test_transform = le.transform(Y_test)

In [ ]:
pca = PCA(n_components=1000)
pca.fit(X_train)
X_train_pca = pca.transform(X_train)
X_test_pca = pca.transform(X_test)

# X_train_pca = np.concatenate((np.ones((X_train_pca.shape[0], 1)), X_train_pca), axis = 1)
# X_test_pca = np.concatenate((np.ones((X_test_pca.shape[0], 1)), X_test_pca), axis = 1)

In [ ]:
all_topic = set(Y_train)
# print(all_topic)
mapping = dict()
for i, t in enumerate(all_topic):
  mapping[t] = i
# print(mapping)
# Y_transform = []
# for c in Y:
#   Y_transform.append(mapping[c])
Y_train_transform = []
for c in Y_train:
  Y_train_transform.append(mapping[c])

Y_test_transform = []
for c in Y_test:
  Y_test_transform.append(mapping[c])

# Naive Bayes

In [ ]:
class MuitinomialNB1():

  def __init__(self):
    self.pc = None
    self.pxc = None
  def fit(self, X, Y):
    """X: ndarray countvectorize (row vector), Y: ndarray label"""
    def compute_pc(Y):
      n = len(Y)
      c = Counter(Y)
      for k in c.keys():
        c[k] /= n
      return c

    self.pc = compute_pc(Y)

    def compute_pxc(X, Y):
      # measure ndarray type
      X = np.asarray(X)
      Y = np.array(Y)
      row, col = X.shape[1], len(self.pc)
      pxc = np.zeros((row, col))
      for c in range(col):
        idx = Y==c
        # print("idx[:10]: ", idx[:10])
        n = sum(idx) # size of class c
        x = X[idx]
        for i in range(row):
          # xi = sum(x[:][i]>0)
          xi = sum(x[:, i])
          pxic = xi/n
          pxc[i][c] = pxic
      return pxc
    self.pxc = compute_pxc(X, Y)
  def predict(self, x): # x: countVectorize
    n = len(self.pc)
    prob = np.zeros(n)
    for i in range(n):
      p = self.pc[i]
      for j in range(len(x)):
        if x[j] > 0:
          p *= self.pxc[j][i]
      prob[i] = p
    return np.argmax(prob)


In [ ]:
bayes = MuitinomialNB1()
bayes.fit(X, Y_transform)

In [ ]:
Y_predict = []
for xi in X:
  Y_predict.append(bayes.predict(xi))

In [ ]:
wr = 0
for a, b in zip(Y_transform, Y_predict):
  if a != b:
    wr += 1
print(1-wr/len(Y_predict))

0.9468500443655723


In [ ]:
from sklearn.metrics import f1_score, confusion_matrix
# f1_score(Y_transform, Y_predict, average='macro') # 0.9529116599715023
confusion_matrix(Y_transform, Y_predict)
# print(mapping.keys())

## Test NB using sklearn

In [ ]:
# using lib
from sklearn.naive_bayes import MultinomialNB
# model = MultinomialNB()
from sklearn.naive_bayes import GaussianNB
gaussian = GaussianNB()
gaussian.fit(X, Y_transform)
Y_predict = []
for xi in X:
  Y_predict.append(bayes.predict(xi))

In [ ]:
# my_prepro = Prepro(4)
# all_data = my_prepro.get_data_from_dir(r"/content/20Newsgroups-classifier/Train/sci.med") 
# all_array_data = []
# for sentence in all_data:
#   s = simple_preprocess(sentence)
#   all_array_data.append(s)
# my_dict = my_prepro.create_dict_from_array(all_array_data)
# print(my_dict)
# joblib.dump(my_dict, "all_dict")

defaultdict(<class 'int'>, {'path': 3, 'cantaloupe': 3, 'srv': 3, 'cs': 6, 'cmu': 5, 'edu': 34, 'das': 1, 'news': 5, 'harvard': 4, 'ogicse': 1, 'emory': 1, 'gatech': 2, 'pitt': 9, 'geb': 4, 'from': 4, 'gordon': 3, 'banks': 3, 'newsgroups': 3, 'sci': 3, 'med': 5, 'subject': 3, 're': 4, 'migraines': 1, 'message': 3, 'id': 3, 'uucp': 2, 'date': 4, 'apr': 6, 'gmt': 3, 'article': 4, 'references': 3, 'mar': 3, 'ntmtv': 1, 'drand': 3, 'spinner': 3, 'osf': 3, 'org': 3, 'sender': 3, 'reply': 1, 'to': 35, 'organization': 3, 'univ': 1, 'of': 37, 'pittsburgh': 1, 'computer': 1, 'science': 1, 'lines': 3, 'in': 18, 'douglas': 1, 'rand': 1, 'writes': 4, 'so': 4, 'll': 3, 'ask': 1, 'this': 8, 'my': 4, 'neurologist': 1, 'just': 4, 'prescribed': 1, 'cafergot': 2, 'and': 22, 'midrin': 1, 'as': 9, 'some': 8, 'alternatives': 1, 'for': 12, 'me': 2, 'try': 3, 'he': 2, 'stated': 1, 'that': 15, 'the': 48, 'sublingual': 1, 'tablets': 2, 'ergotamine': 1, 'were': 2, 'no': 9, 'longer': 3, 'available': 2, 'any': 10

['all_dict']

#### tfidf load and transform

In [ ]:
# test tfidf lib
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
X_tfidf_train = joblib.load("/content/drive/My Drive/X_tfidf_train.lfs")
Y_tfidf_train = joblib.load("/content/drive/My Drive/Y_tfidf_train")
le.fit(Y_tfidf_train)
Y_tfidf_train = le.transform(Y_tfidf_train)

X_tfidf_test = joblib.load("/content/drive/My Drive/X_tfidf_test.lfs")
Y_tfidf_test = joblib.load("/content/drive/My Drive/Y_tfidf_test")
Y_tfidf_test = le.transform(Y_tfidf_test)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_tfidf_train, Y_tfidf_train)
my_y_tfidf_predict = model.predict(X_tfidf_train)

In [ ]:
# accuracy_score(my_y_tfidf_predict, Y_tfidf_train)
my_y_tfidf_predict_test = model.predict(X_tfidf_test)
accuracy_score(my_y_tfidf_predict_test, Y_tfidf_test)

0.7964814074370252

# logistic regression

## softmax regression

In [ ]:
import numpy as np
from copy import deepcopy
# n: number of feature, m: number of data train
# c: number of class
# m: number of train data
# X(n+1, m): data train column matrix, (append row [1,1,1...] for b0)
# W(n+1, c) : weight
# Y(c, m): labels matrix, each column is one hot vector, sf labels for 1 observation
# Y_predict(c, m): predict labels, shape = shape(Y), each column is probality vector 
# ()

class SoftmaxRegression():
  def __init__(self, lr=0.05, tol=1e-4, max_iter=1000, print_after=100):
    self.lr = lr # learning rate
    self.tol = tol # tolerance
    self.max_iter = max_iter # max iteration
    self.print_after = print_after
    self.w = None
  
  def linear(self, W, X):
    """return (c, m)"""
    return np.dot(W.T, X) # Z
  
  def sigmoid(self, Z):
    """return (c, m)"""
    return np.exp(Z) # A
  
  def softmax(self, Z):
    """return (c, m)"""
    A = self.sigmoid(Z)
    return A / np.sum(A, axis=0)
  
  def softmax_new(self, Z):
    """return (c, m)"""
    Z_min = np.max(Z, axis=0, keepdims=True)
    Z_ = Z - Z_min
    A = self.sigmoid(Z_)
    return A / np.sum(A, axis=0)
  
  def cross_entropy(self, Y_predict, Y):
  # """return (1, m)"""
    return np.multiply(Y, np.log(Y_predict)) # * for elememtwise is ok too

  def cost(self, W, X, Y):
    """ return scalar"""
    Z = self.linear(W, X)
    Y_predict = self.softmax_new(Z)
    return -np.sum(self.cross_entropy(Y_predict, Y))

  def grad(self, W, X, Y):
    """dw return (n, c)"""
    Z = self.linear(W, X)
    # print("z: ", Z)
    Y_predict = self.softmax_new(Z)
    # print("predict: ", Y_predict)
    return np.dot(X, (Y_predict - Y).T)

  def fit(self, X, Y, w_init=[]):
    """X, Y: ndarray"""
    X = np.asarray(X)
    Y = np.asarray(Y)
    c = Y.shape[0] # number of class
    m = Y.shape[1] # no of observation
    n = X.shape[0] # number of feature
    idx = np.array([i for i in range(m)])
    if len(w_init) == 0:
      w_init = np.random.randn(X.shape[0], Y.shape[0])
    w = w_init
    loop = 0
    print_after = self.print_after
    while loop < self.max_iter:
      loop += 1
      np.random.shuffle(idx)
      for i in idx:
        x = X[:, i].reshape(n, 1)
        y = Y[:, i].reshape(c, 1)
        w1 = deepcopy(w)
        w -= self.lr * self.grad(w1, x, y) 
        if loop % print_after == 0:
          # print("cost: ", self.cost(w1, X, Y))
          if np.linalg.norm(w1-w) < self.tol:
            self.w = w
            return
    self.w = w
# batch, epochs, l2
  def predict(self, X):
    """X:column matrix"""
    X = np.asarray(X)
    Y_predict = []
    for x in X.T:
      # x = np.asarray(x).reshape(-1,1)
      z = self.linear(self.w, x)
      y = self.softmax_new(z)
      Y_predict.append(np.argmax(y))
    return Y_predict
  def predict_origin(self, x):
    z = self.linear(self.w, x)
    y = self.softmax_new(z)
    return np.argmax(y)
    

In [ ]:
from scipy import sparse
def convert_labels(y, C):
    Y = sparse.coo_matrix((np.ones_like(y), 
        (y, np.arange(len(y)))), shape = (C, len(y))).toarray()
    return Y 

Y_tfidf_train_soft_max = convert_labels(Y_tfidf_train, 20)

In [ ]:
model = SoftmaxRegression(max_iter=100, print_after=10)
# w = np.random.randn(m, c)
X_tfidf_train_soft_max = np.array(X_tfidf_train.toarray())

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
model.fit(X_tfidf_train_soft_max.T, Y_tfidf_train_soft_max)

In [ ]:
y_tfidf_train_soft_max_predict = model.predict(X_tfidf_train_soft_max.T)

In [ ]:
accuracy_score(y_tfidf_train_soft_max_predict, Y_tfidf_train)

0.773114463176575

In [ ]:
Y2 = []
for c in Y:
  Y2.append(mapping[c])

In [ ]:
count = 0
for a, b in zip(tst, Y2):
  if a== b:
    count += 1

In [ ]:
count/len(Y2)

0.5059449866903283

## logistic regression for multi label

In [ ]:
import copy
class LogisticRegression1():
  
  def __init__(self, lr=0.05, lambd=1e-4, epochs=500):
    self.lr = lr
    self.lambd = lambd 
    self.epochs=epochs
    self.w = []

  def linear(self, W, X):
    """return (c, m)"""
    return np.dot(W.T, X) # Z
  
  def sigmoid(self, Z):
    """return (c, m)"""
    return 1/ (1+np.exp(-Z)) # A
  
  def grad(self, W, X, Y):
    Z = self.linear(W, X)
    A = self.sigmoid(Z)
    # return np.multiply((A-Y), X)
    return np.multiply((A-Y), X) + self.lambd * W

  
  def fit(self, X, Y, w_init=[]):
    d = X.shape[0]
    m = X.shape[1]
    if len(w_init) == 0:
      w_init = np.random.randn(d, 1)
    w0 = w_init
    all_idx = np.array([i for i in range(m)])
    loop = 0
    max_loop = self.epochs
    while(loop<max_loop):
      # start = time()
      all_idx = np.random.permutation(all_idx)
      for i in all_idx:
        xi = X[:, i].reshape(d, 1)
        yi = Y[i]
        # w_new = w0.reshape(d, 1) - self.lr * self.grad(w0, xi, yi).reshape(d, 1)
        # t0_grad = time()
        w_new = w0 - self.lr * self.grad(w0, xi, yi)
        # t1_grad = time()
        # print(f"compute grad after{t1_grad-t0_grad}")
        w0 = copy.deepcopy(w_new)
      end = time()
      # print(f"done loop {loop} after {end-start}s")
      loop += 1
    # self.w = w0
    return w0
  
  def fit_all(self, X, Y, w_init=[]):
    """
    Y: label, range(0, c)
    X, W: colmn matrix
    """
    X = np.array(X)
    Y = np.array(Y)
    classes = set(Y) # range(1, c)
    c = len(classes) # nof class
    d = X.shape[0] # dimension
    m = X.shape[1] # nof train data

    if len(w_init) == 0:
      w_init = np.random.randn(d, c)
    
    w = np.array([])
    # 1 vs rest.
    for idx in range(c):
      t1 = time()
      Y_train_tmp = Y == idx
      wc = self.fit(X, Y_train_tmp, w_init[:, idx].reshape(d, 1))
      # print("shape wc: ", wc.shape)
      w = np.append(w, [wc])
      # print(f"w[{idx}]: ", wc)
      t2 = time()
      print(f"done class {idx} after {t2-t1}s!\n")
    self.w = w.reshape(d,c, order='F')

  # def predict(self, X):
  #   Z = self.linear(self.w, X)
  #   A = self.sigmoid(Z)
  #   return A

  def predict(self, x):
    Z = np.dot(self.w.T, x)
    A = self.sigmoid(Z)
    # print(A)
    return np.argmax(A, axis=0)

In [ ]:
import copy
class LogisticRegression1():
  
  def __init__(self, lr=0.05, lambd=1e-5, batch=64, epochs=500):
    self.lr = lr
    self.lambd = lambd 
    self.batch = batch
    self.epochs = epochs
    self.w = []

  def linear(self, W, X):
    """return (c, m)"""
    return np.dot(W.T, X) # Z
  
  def sigmoid(self, Z):
    """return (c, m)"""
    return 1/ (1+np.exp(-Z)) # A
  
  def grad(self, W, X, Y):
    Z = self.linear(W, X)
    A = self.sigmoid(Z)
    # return (A-Y) * X
    return np.average(np.multiply((A-Y), X), axis=1) + self.lambd * W

  
  def fit(self, X, Y, w_init=[]):
    d = X.shape[0]
    m = X.shape[1]
    if len(w_init) == 0:
      w_init = np.random.randn(d, 1)
    w0 = w_init
    all_idx = np.array([i for i in range(m)])
    loop = 0
    max_loop = self.epochs

    k = m // self.batch

    while(loop<max_loop):
      # start = time()
      all_idx = np.random.permutation(all_idx)
      for i in range(k):
        current_idx = all_idx[self.batch*i:self.batch*(i+1)]
        xi = X[:, current_idx] #.reshape(d, 1)
        yi = Y[current_idx]
        # w_new = w0.reshape(d, 1) - self.lr * self.grad(w0, xi, yi).reshape(d, 1)
        # t0_grad = time()
        w_new = w0 - self.lr * self.grad(w0, xi, yi)
        # t1_grad = time()
        # print(f"compute grad after{t1_grad-t0_grad}")
        w0 = copy.deepcopy(w_new)
      # end = time()
      # print(f"done loop {loop} after {end-start}s")
      loop += 1
    # self.w = w0
    return w0
  
  def fit_all(self, X, Y, w_init=[]):
    """
    Y: label, range(0, c)
    X, W: colmn matrix
    """
    X = np.array(X)
    Y = np.array(Y)
    classes = set(Y) # range(1, c)
    c = len(classes) # nof class
    d = X.shape[0] # dimension
    m = X.shape[1] # nof train data

    if len(w_init) == 0:
      w_init = np.random.randn(d, c)
    
    w = np.array([])
    # 1 vs rest.
    for idx in range(c):
      t1 = time()
      Y_train_tmp = Y == idx
      wc = self.fit(X, Y_train_tmp, w_init[:, idx].reshape(d, 1))
      # print("shape wc: ", wc.shape)
      w = np.append(w, [wc])
      # print(f"w[{idx}]: ", wc)
      t2 = time()
      print(f"done class {idx} after {t2-t1}s!\n")
    self.w = w.reshape(d,c, order='F')

  # def predict(self, X):
  #   Z = self.linear(self.w, X)
  #   A = self.sigmoid(Z)
  #   return A

  def predict(self, x):
    Z = np.dot(self.w.T, x)
    A = self.sigmoid(Z)
    # print(A)
    return np.argmax(A, axis=0)

In [ ]:
from time import time
t1 = time()
my_model = LogisticRegression1()
my_model.fit_all(X_train_pca.T, Y_train_transform)
my_y_train_predict = my_model.predict(X_train_pca.T)
my_y_test_predict = my_model.predict(X_test_pca.T)
t2 = time()
print(f"train and predict done after: {t2-t1}s")

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: RuntimeWarning: overflow encountered in exp
  app.launch_new_instance()


done class 0 after 141.02648043632507s!

done class 1 after 140.82420539855957s!

done class 2 after 139.83836245536804s!

done class 3 after 141.41368412971497s!

done class 4 after 141.84718585014343s!

done class 5 after 141.0386447906494s!

done class 6 after 142.31522798538208s!

done class 7 after 140.42853379249573s!

done class 8 after 140.2455861568451s!

done class 9 after 141.56627535820007s!

done class 10 after 141.48139810562134s!

done class 11 after 141.45578050613403s!

done class 12 after 141.18538522720337s!

done class 13 after 142.58256077766418s!

done class 14 after 140.83732151985168s!

done class 15 after 141.08490633964539s!

done class 16 after 140.5986840724945s!

done class 17 after 141.15088891983032s!

done class 18 after 142.03147506713867s!

done class 19 after 141.83304715156555s!

train and predict done after: 2825.0558116436005s


without regularization, SGD:
- training time: 488 s
- mymodel:
  - train accuracy: 0.9740017746228926
  - test accuracy: 0.7083833133413301
- sklearn model: 
  - train accuracy: 0.9940023990403839
  - test accuracy: 0.711182193789151

In [ ]:
print(accuracy_score(my_y_train_predict, Y_train_transform))
print(accuracy_score(my_y_test_predict, Y_test_transform))

0.8695652173913043
0.6783953085432494


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([[0, 2, 3, 4], [1, 2, 3, 4]])
print(a)
print(b)
print(a*b)

[1 2 3 4]
[[0 2 3 4]
 [1 2 3 4]]
[[ 0  4  9 16]
 [ 1  4  9 16]]


### test using sklearn and tf-idf vectorize

In [ ]:
from sklearn.linear_model import LogisticRegression

model_lr_sklearn = LogisticRegression(C=10, max_iter=500)
model_lr_sklearn.fit(X_tfidf_train, Y_tfidf_train)


LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=500,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
my_y_train_tfidf_predict = model_lr_sklearn.predict(X_tfidf_train)
print(accuracy_score(my_y_train_tfidf_predict, Y_tfidf_train))

my_y_test_tfidf_predict = model_lr_sklearn.predict(X_tfidf_test)
print(accuracy_score(my_y_test_tfidf_predict, Y_tfidf_test))

# c=1: 
# 0.9740017746228926
# 0.8300679728108756
# c=2
# max_iter=200
# 0.9943212067435669
# 0.8412634946021591
# c=10
# 0.9991126885536823
# 0.8423297347727575

0.9991126885536823
0.8423297347727575


#### using pca:

In [ ]:
from sklearn.decomposition import TruncatedSVD
svd_tfidf = TruncatedSVD(n_components=2000)
svd_tfidf.fit(X_tfidf_train)
X_train_pca = svd_tfidf.transform(X_tfidf_train)
X_test_pca = svd_tfidf.transform(X_tfidf_test)

X_tfidf_train_pca = np.concatenate((np.ones((X_train_pca.shape[0], 1)), X_train_pca), axis = 1)
X_tfidf_test_pca = np.concatenate((np.ones((X_test_pca.shape[0], 1)), X_test_pca), axis = 1)

In [ ]:
from sklearn.linear_model import LogisticRegression
model_lr_sklearn_svd = LogisticRegression(C=10, max_iter=500)
model_lr_sklearn_svd.fit(X_tfidf_train_pca, Y_tfidf_train)

LogisticRegression(C=10, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=500,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
my_y_train_tfidf_predict = model_lr_sklearn_svd.predict(X_tfidf_train_pca)
print(accuracy_score(my_y_train_tfidf_predict, Y_tfidf_train))

my_y_test_tfidf_predict = model_lr_sklearn_svd.predict(X_tfidf_test_pca)
print(accuracy_score(my_y_test_tfidf_predict, Y_tfidf_test))
# c=1
# 0.9464063886424134
# 0.8170065307210449
# c=0.5
# 0.9224489795918367
# 0.8087431693989071
# C=5
# 0.9827861579414374
# 0.83046781287485
# c=10
# 0.9917480035492457
# 0.831134212981474

0.9917480035492457
0.831134212981474


In [ ]:
# my model
from time import time
t1 = time()
my_model = LogisticRegression1(lambd=0)
my_model.fit_all(X_tfidf_train_pca.T, Y_tfidf_train)
my_y_train_predict = my_model.predict(X_tfidf_train_pca.T)
my_y_test_predict = my_model.predict(X_tfidf_test_pca.T)
t2 = time()
print(f"train and predict done after: {t2-t1}s")

done class 0 after 159.36784434318542s!

done class 1 after 160.41769528388977s!

done class 2 after 159.56728410720825s!

done class 3 after 159.61383414268494s!

done class 4 after 159.84790682792664s!

done class 5 after 159.8946452140808s!

done class 6 after 160.66920280456543s!

done class 7 after 159.25117993354797s!

done class 8 after 158.53119707107544s!

done class 9 after 158.91223001480103s!

done class 10 after 159.04833436012268s!

done class 11 after 159.09519791603088s!

done class 12 after 160.72660875320435s!

done class 13 after 158.76486921310425s!

done class 14 after 158.82722568511963s!

done class 15 after 159.17305278778076s!

done class 16 after 158.65871024131775s!

done class 17 after 160.78442478179932s!

done class 18 after 158.0179316997528s!

done class 19 after 158.43036770820618s!

train and predict done after: 3187.751258134842s


In [ ]:
print(accuracy_score(my_y_train_predict, Y_tfidf_train))
print(accuracy_score(my_y_test_predict, Y_tfidf_test))
# lambd = 1e-4, num epochs = 500 => t=3300
# 0.9300798580301686
# 0.8075436492069838
# lambd = 0
# 0.9961845607808341
# 0.8290017326402772

0.9961845607808341
0.8290017326402772


# Kmeans

In [ ]:
from scipy.spatial.distance import cdist
import logging

class KMeans1():
  # all array use below are ndarray, no comment!
  def __init__(self, n_clusters):
    self.n_clusters = n_clusters
    self.cluster_centers_ = None
    self.logger = logging.getLogger()
  def fit(self, X):
    # X: row data
    n, d = X.shape

    # random init labels
    Y = np.random.randint(0, self.n_clusters, n)

    # place holder center
    centers = np.zeros((self.n_clusters, d))

    count = 0
    while count<1000:
      self.logger.warning(f"------------------------\n\n")
      self.logger.warning(f"counter: {Counter(Y)}!")
      count+= 1
      # if count % 10 == 0:
      #   self.logger.warning(f"loop {count}!")
      # compute new center:
      for i in range(self.n_clusters):
        centers[i] = np.mean(X[Y==i], axis=0)
      
      # assign class
      ## compute distance to center
      distance_matrix = cdist(X, centers)
      ## assign new label
      Y_new = np.argmin(distance_matrix, axis=1)
      if (Y_new == Y).all():
        print(f"break after {count} iterations")
        break
      Y = np.copy(Y_new)

    self.cluster_centers_ = centers
    # return Y

  def predict(self, X):
    distance_matrix = cdist(X, self.cluster_centers_)
    labels = np.argmin(distance_matrix, axis=1)
    return labels

  @staticmethod
  def score(Y_true, Y_predict):
    # assume: max true
    # consider input order
    n_clusters = len(set(Y_true))
    Y_true_transform = np.zeros_like(Y_true)
    Y_predict_transform = np.copy(Y_predict)
    Y_predict_copy = np.copy(Y_predict)

    for i in range(n_clusters):
      yi = Y_true==i
      yi_pred = Y_predict_copy[yi]
      i_map = max(Counter(yi_pred).items(), key=lambda x: x[1] if x[0] >= 0 else -1)[0] # become positive ok!
      Y_true_transform[yi] = i_map
      Y_predict_copy[Y_predict_copy==i_map] = -1 # mark, change Y_predict here
    
    sc = accuracy_score(Y_true_transform, Y_predict_transform)
    return sc


In [ ]:
from sklearn.decomposition import TruncatedSVD

svd = TruncatedSVD(n_components=10000)
svd.fit(X_train_tfidf)
X_train_svd = svd.transform(X_train_tfidf)
# X_test_svd = svd.transform(X_test)

In [ ]:
from sklearn.cluster import KMeans

from time import time
t1 = time()
kmeans = KMeans(n_clusters=20, random_state=0).fit(X_train_tfidf)
t2 = time()
print(f"training time: {t2-t1}")
print('Centers found by scikit-learn:')
print(kmeans.cluster_centers_)
pred_label = kmeans.predict(X_train_tfidf)
pred_label_test = kmeans.predict(X_test_tfidf)

training time: 575.2834944725037
Centers found by scikit-learn:
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [4.00057922e-06 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]]


In [ ]:
model = KMeans1(20)
t1 = time()
model.fit(X_train_tfidf.toarray())
t2 = time()
print(f"training after: {t2-t1}s")
lbs = model.predict(X_train_tfidf.toarray())
lbs_test = model.predict(X_test_tfidf.toarray())

------------------------


counter: Counter({12: 589, 9: 587, 3: 582, 10: 578, 1: 578, 4: 576, 5: 576, 6: 576, 7: 570, 2: 568, 16: 567, 14: 557, 0: 555, 18: 551, 8: 550, 19: 550, 15: 550, 11: 540, 13: 538, 17: 532})!
------------------------


counter: Counter({6: 674, 9: 644, 0: 625, 3: 606, 2: 599, 7: 596, 12: 584, 5: 576, 15: 571, 19: 562, 11: 560, 18: 543, 16: 526, 8: 522, 10: 521, 1: 519, 14: 519, 4: 514, 13: 507, 17: 502})!
------------------------


counter: Counter({18: 821, 3: 783, 19: 740, 15: 728, 5: 725, 12: 648, 9: 619, 2: 553, 16: 551, 11: 533, 13: 501, 7: 488, 8: 484, 6: 483, 17: 477, 1: 460, 0: 448, 4: 426, 14: 403, 10: 399})!
------------------------


counter: Counter({18: 1001, 15: 970, 19: 897, 3: 853, 5: 771, 16: 612, 12: 580, 14: 539, 9: 515, 2: 513, 10: 510, 13: 510, 17: 497, 11: 418, 8: 416, 7: 403, 4: 376, 0: 328, 6: 290, 1: 271})!
------------------------


counter: Counter({15: 1145, 18: 1112, 19: 1034, 3: 780, 14: 766, 5: 746, 16: 659, 10: 636, 12: 538, 2: 4

training after: 180.50415587425232s


In [ ]:
def compute_purity(predicted,expected):
  majority_sum=0
  for cluster_index in range(20):
    member_indexs=np.where(predicted==cluster_index)[0]
    expected_labels=[expected[index]for index in member_indexs]
    max_count=max(expected_labels.count(la)for la in range(20))
    majority_sum+=max_count
  print(majority_sum)
  return majority_sum/len(expected)

In [ ]:
compute_purity(lbs_test, Y_test_transform)
# train: 0.3801242236024845, time: 575.2834944725037
# test: 0.20488021295474712

# my model:
# train: 180.50415587425232s,  0.4200532386867791
# test: 0.351192856190857

2635


0.351192856190857

# SVM

In [ ]:
X_train_tfidf.shape

(11270, 70733)

In [ ]:
from sklearn.svm import SVC
from time import time
svc = SVC(kernel='linear', gamma='auto', C=0.1)
# C=1.0, kernel='linear', degree=3, gamma='auto'
t1 = time()
svc.fit(X_train_tfidf, Y_train_transform)
t2 = time()
print(f"done after {t2-t1} s") # rbf: 260s, poly: 300.9100682735443 s, linear: 120.51525282859802 s
y_train_pred = svc.predict(X_train_tfidf)
y_test_pred = svc.predict(X_test_tfidf)

done after 217.05814266204834 s


In [ ]:
print(accuracy_score(y_train_pred, Y_train_transform))
print(accuracy_score(y_test_pred, Y_test_transform))
# c default: 
# rbf:
# 0.9965394853593611
# 0.8260695721711315

# poly:
# 0.9990239574090506
# 0.5913634546181528

# c=5, rbf:
# 0.9993788819875776
# 0.8279354924696788

# linear:
# 0.9899733806566104
# 0.8295348527255765

0.860958296362023
0.726109556177529


In [ ]:
# not using now
from sklearn.decomposition import TruncatedSVD
svd_tfidf = TruncatedSVD(n_components=20000)
t1 = time()
svd_tfidf.fit(X_train_tfidf)
t2 = time()
print(f"{t2-t1}s done!")
X_train_tfidf_svd = svd_tfidf.transform(X_train_tfidf)

# Neural network with pytorch

## Classical neural network

In [ ]:
import torch
from torch.autograd import Variable
from torchsummary import summary
from time import time

In [ ]:
class Softmax(torch.nn.Module):
  def __init__(self, input_dim, output_dim):
    super(Softmax, self).__init__()
    self.linear = torch.nn.Linear(input_dim, output_dim)
    self.activate1 = torch.nn.Sigmoid()
    self.activate2 = torch.nn.Softmax(dim=1)
  
  def forward(self, x):
    out = self.linear(x)
    out = self.activate1(out)
    out = self.activate2(out)

    return out

In [ ]:
X_train_tfidf.shape, Y_train_transform.shape

((11270, 24888), (11270,))

In [ ]:
model = Softmax(24888, 20)
if torch.cuda.is_available():
    model.cuda()

criterion = torch.nn.CrossEntropyLoss()
lr = 0.005
optimizer = torch.optim.Adam(model.parameters(), lr)

epochs = 100
t1 = time()
for epoch in range(epochs):
  if torch.cuda.is_available():
    X = Variable(torch.from_numpy(X_train_tfidf.toarray()).float().cuda())
    Y = Variable(torch.from_numpy(Y_train_transform).cuda())
  else:
    X = Variable(torch.from_numpy(X_train_tfidf.toarray()).float())
    Y = Variable(torch.from_numpy(Y_train_transform))
  optimizer.zero_grad()

  output = model(X)
  loss = criterion(output, Y)
  loss.backward()
  optimizer.step()
  if epoch % 10 == 0:
    print(f"loss after {epoch} epochs: {loss}")

print(f"train {epoch} epochs after {time()-t1} s") 

In [ ]:
pred = torch.argmax(model(torch.from_numpy(X_train_tfidf.toarray()).float().cuda()), axis=1)
sum(pred == torch.from_numpy(Y_train_transform).cuda())

tensor(11091, device='cuda:0')

In [ ]:
pred = torch.argmax(model(torch.from_numpy(X_test_tfidf.toarray()).float().cuda()), axis=1)
sum(pred == torch.from_numpy(Y_test_transform).cuda())

tensor(5968, device='cuda:0')

In [ ]:
# softmax: traintime: 3s
# 11090/11270 = 0.9840283939662822
# 5968/7503 = 0.7954151672664268

0.9840283939662822

In [ ]:
model = Softmax(24888, 20)
summary(model, (49776, 24888))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1            [-1, 49776, 20]         497,780
           Sigmoid-2            [-1, 49776, 20]               0
           Softmax-3            [-1, 49776, 20]               0
Total params: 497,780
Trainable params: 497,780
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 4725.74
Forward/backward pass size (MB): 22.79
Params size (MB): 1.90
Estimated Total Size (MB): 4750.43
----------------------------------------------------------------


In [ ]:
class SoftmaxMs(torch.nn.Module):
  def __init__(self, input_dim, output_dim):
    super(SoftmaxMs, self).__init__()
    self.linear1 = torch.nn.Linear(input_dim, 200)
    self.activ1 = torch.nn.ReLU()
    self.linear2 = torch.nn.Linear(200, 100)
    self.activ2 = torch.nn.ReLU()
    self.linear3 = torch.nn.Linear(100, output_dim)
    self.activ3 = torch.nn.Sigmoid()

    self.activend = torch.nn.Softmax(dim=1)

    self.batchnorm2 = torch.nn.BatchNorm1d(200)
    self.dropout1 = torch.nn.Dropout(0.4)
    self.dropout2 = torch.nn.Dropout(0.3)

  def forward(self, x):
    output = self.linear1(x)
    output = self.activ1(output)
    output = self.dropout1(output)

    output = self.batchnorm2(output) 
    output = self.linear2(output)
    output = self.activ2(output)
    output = self.dropout2(output)

    output = self.linear3(output)
    output = self.activ3(output)
    output = self.activend(output)

    return output

In [ ]:
model = SoftmaxEvol(24888, 20)
if torch.cuda.is_available():
    model.cuda()

criterion = torch.nn.CrossEntropyLoss()
lr = 0.005
optimizer = torch.optim.Adam(model.parameters(), lr)

epochs = 31
from time import time
t1 = time()
for epoch in range(epochs):
  if torch.cuda.is_available():
    X = Variable(torch.from_numpy(X_train_tfidf.toarray()).float().cuda())
    Y = Variable(torch.from_numpy(Y_train_transform).cuda())
  else:
    X = Variable(torch.from_numpy(X_train_tfidf.toarray()).float())
    Y = Variable(torch.from_numpy(Y_train_transform))
  optimizer.zero_grad()

  output = model(X)
  loss = criterion(output, Y)
  loss.backward()
  optimizer.step()
  if epoch % 2 == 0:
    print(f"loss after {epoch} epochs: {loss}")
    pred1 = torch.argmax(model(torch.from_numpy(X_train_tfidf.toarray()).float().cuda()), axis=1)
    s1 = sum(pred1 == torch.from_numpy(Y_train_transform).cuda())
    print(f"true train: {s1}")

    pred2 = torch.argmax(model(torch.from_numpy(X_test_tfidf.toarray()).float().cuda()), axis=1)
    s2 = sum(pred2 == torch.from_numpy(Y_test_transform).cuda())
    print(f"true test: {s2}")

print(f"training {epochs} epochs done after {time()-t1} s")

loss after 0 epochs: 2.9957852363586426
true train: 7370
true test: 3815
loss after 2 epochs: 2.980170726776123
true train: 9947
true test: 5346
loss after 4 epochs: 2.9692044258117676
true train: 10439
true test: 5630
loss after 6 epochs: 2.9583020210266113
true train: 10689
true test: 5803
loss after 8 epochs: 2.9477012157440186
true train: 10871
true test: 5856
loss after 10 epochs: 2.9381468296051025
true train: 11010
true test: 5959
loss after 12 epochs: 2.930889844894409
true train: 11096
true test: 5988
loss after 14 epochs: 2.9269700050354004
true train: 11158
true test: 6054
loss after 16 epochs: 2.9248554706573486
true train: 11208
true test: 6071
loss after 18 epochs: 2.9233345985412598
true train: 11235
true test: 6091
loss after 20 epochs: 2.922386646270752
true train: 11245
true test: 6113
loss after 22 epochs: 2.921751022338867
true train: 11254
true test: 6136
loss after 24 epochs: 2.921435832977295
true train: 11255
true test: 6097
loss after 26 epochs: 2.9212393760681

In [ ]:
11260/11270, 6136/7503

(0.9991126885536823, 0.8178062108489937)

In [ ]:
model = SoftmaxMs(24888, 20)
summary(model, (49776, 24888))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1           [-1, 49776, 200]       4,977,800
              ReLU-2           [-1, 49776, 200]               0
           Dropout-3           [-1, 49776, 200]               0
            Linear-4           [-1, 49776, 100]          20,100
              ReLU-5           [-1, 49776, 100]               0
           Dropout-6           [-1, 49776, 100]               0
            Linear-7            [-1, 49776, 20]           2,020
           Sigmoid-8            [-1, 49776, 20]               0
           Softmax-9            [-1, 49776, 20]               0
Total params: 4,999,920
Trainable params: 4,999,920
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 4725.74
Forward/backward pass size (MB): 364.57
Params size (MB): 19.07
Estimated Total Size (MB): 5109.39
------------------------------

In [ ]:
class SoftmaxMess(torch.nn.Module):
  def __init__(self, input_dim, output_dim):
    super(SoftmaxMess, self).__init__()
    self.batchnorm1 = torch.nn.BatchNorm1d(input_dim)
    self.linear1 = torch.nn.Linear(input_dim, 500)
    self.activ1 = torch.nn.ReLU()


    self.dropout2 = torch.nn.Dropout(0.5)
    self.linear2 = torch.nn.Linear(500, 20)
    self.activ2 = torch.nn.LogSigmoid()


  def forward(self, x):
    output = self.batchnorm1(x)
    output = self.linear1(output)
    output = self.activ1(output)

    output = self.dropout2(output) 
    output = self.linear2(output)
    output = self.activ2(output)

    return output

In [ ]:
model = SoftmaxMess(24888, 20)
if torch.cuda.is_available():
    model.cuda()

criterion = torch.nn.CrossEntropyLoss()
lr = 0.005
optimizer = torch.optim.Adam(model.parameters(), lr)

epochs = 51
from time import time
t1 = time()
for epoch in range(epochs):
  if torch.cuda.is_available():
    X = Variable(torch.from_numpy(X_train_tfidf.toarray()).float().cuda())
    Y = Variable(torch.from_numpy(Y_train_transform).cuda())
  else:
    X = Variable(torch.from_numpy(X_train_tfidf.toarray()).float())
    Y = Variable(torch.from_numpy(Y_train_transform))
  optimizer.zero_grad()

  output = model(X)
  loss = criterion(output, Y)
  loss.backward()
  optimizer.step()
  if epoch % 10 == 0:
    print(f"loss after {epoch} epochs: {loss}")
    pred1 = torch.argmax(model(torch.from_numpy(X_train_tfidf.toarray()).float().cuda()), axis=1)
    s1 = sum(pred1 == torch.from_numpy(Y_train_transform).cuda())
    print(f"true train: {s1}")

    pred2 = torch.argmax(model(torch.from_numpy(X_test_tfidf.toarray()).float().cuda()), axis=1)
    s2 = sum(pred2 == torch.from_numpy(Y_test_transform).cuda())
    print(f"true test: {s2}")

print(f"training {epochs} epochs done after {time()-t1} s")

loss after 0 epochs: 3.002722978591919
true train: 10784
true test: 5774
loss after 10 epochs: 0.006617544684559107
true train: 11241
true test: 5892
loss after 20 epochs: 0.004890852607786655
true train: 11253
true test: 5890
loss after 30 epochs: 0.006686647888273001
true train: 11257
true test: 5949
loss after 40 epochs: 0.004518006928265095
true train: 11254
true test: 5979
loss after 50 epochs: 0.004200186114758253
true train: 11261
true test: 5948
training 51 epochs done after 69.87499022483826 s


## CNN with pytorch

In [ ]:
from sklearn.decomposition import TruncatedSVD
svd = TruncatedSVD(n_components=1000)
svd.fit(X_train_tfidf)
X_train = svd.transform(X_train_tfidf)
X_test = svd.transform(X_test_tfidf)


In [ ]:
class CNNModel(torch.nn.Module):
    def __init__(self, input_dim, n_class):
        super(CNNModel, self).__init__()
        self.conv1 = torch.nn.Conv1d(in_channels=1, out_channels=24, kernel_size=5, stride=1, padding=2) # 24 input
        self.relu1 = torch.nn.ReLU()
        self.conv2 = torch.nn.Conv1d(in_channels=24, out_channels=32, kernel_size=3, stride=1, padding=1) # 32 input
        self.relu2 = torch.nn.ReLU()
        self.maxpool1 = torch.nn.MaxPool1d(kernel_size=2, stride=2, padding=0) # 16 input
        self.conv3 = torch.nn.Conv1d(in_channels=32, out_channels=48, kernel_size=3, stride=1, padding=1) # 24 input
        self.maxpool2 = torch.nn.MaxPool1d(kernel_size=4, stride=4) # 8 input

        self.fc1 = torch.nn.Linear(input_dim * 6, out_features=n_class)
        self.activ1 = torch.nn.Softmax(dim=1)
    
    def forward(self, x):
        out = self.conv1(x)
        # print(out.shape)
        out = self.relu1(out)
        out = self.conv2(out)
        # print(out.shape)
        out = self.relu2(out)
        out = self.maxpool1(out)
        out = self.conv3(out)
        # print(out.shape)
        out = self.maxpool2(out)
        # print(out.shape)
        out = self.fc1(out.view(out.shape[0], -1))
        out = self.activ1(out)
        
        return out
    


In [ ]:
from torch.utils.data import Dataset, DataLoader
class DataUtils(Dataset):
    def __init__(self):
        self.x = torch.from_numpy(X_train).float()
        self.y = torch.from_numpy(Y_train_transform)
        self.length = self.x.shape[0]

    def __getitem__(self, index):    
        return self.x[index],self.y[index]

    def __len__(self):
        return self.length

dataset = DataUtils()
trainloader=DataLoader(dataset=dataset,batch_size=128, shuffle=True)

In [ ]:
torch.cuda.empty_cache()
model = CNNModel(1000, 20)
if torch.cuda.is_available():
    model.cuda()

criterion = torch.nn.CrossEntropyLoss()
lr = 0.005
optimizer = torch.optim.Adam(model.parameters(), lr)

epochs = 101
from time import time
t1 = time()
for epoch in range(epochs):
    for X, Y in trainloader:
        if torch.cuda.is_available():
            X = Variable(X.view(X.shape[0], 1, X.shape[1]).cuda())
            Y = Variable(Y.cuda())
        else:
            X = Variable(X.shape[0], 1, X.shape[1])
            Y = Variable(Y)
        
        optimizer.zero_grad()

        output = model(X)
        loss = criterion(output, Y)
        loss.backward()
        optimizer.step()
    if epoch % 5 == 0:
        # CUDA out of memory. ==>
        print(f"loss after {epoch} epochs: {loss}")
        pred1 = torch.argmax(model(torch.from_numpy(X_train[:1000]).view(X_train[:1000].shape[0], 1, X_train[:1000].shape[1]).float().cuda()), axis=1)
        s1 = sum(pred1 == torch.from_numpy(Y_train_transform[:1000]).cuda())
        print(f"true train: {s1}")

        # pred2 = torch.argmax(model(torch.from_numpy(X_test).view(X_test.shape[0], 1, X_test.shape[1]).float().cuda()), axis=1)
        # s2 = sum(pred2 == torch.from_numpy(Y_test_transform).cuda())
        # print(f"true test: {s2}")

print(f"training {epochs} epochs done after {time()-t1} s")

In [ ]:
# CUDA out of memory. ==>
batch_predict = 1000
e_train = X_train.shape[0] // 1000
e_test = X_test.shape[0] // 1000
train_true = 0
test_true = 0
for i in range(e_train):
    my_x = X_train[batch_predict * i: batch_predict*(i+1)]
    pred1 = torch.argmax(model(torch.from_numpy(my_x).view(my_x.shape[0], 1, my_x.shape[1]).float().cuda()), axis=1)
    s1 = sum(pred1 == torch.from_numpy(Y_train_transform[batch_predict * i: batch_predict*(i+1)]).cuda())
    train_true += s1
for i in range(e_test):    
    my_x = X_test[batch_predict * i: batch_predict*(i+1)]
    pred2 = torch.argmax(model(torch.from_numpy(my_x).view(my_x.shape[0], 1, my_x.shape[1]).float().cuda()), axis=1)
    s2 = sum(pred2 == torch.from_numpy(Y_test_transform[batch_predict * i: batch_predict*(i+1)]).cuda())
    test_true += s2

print(f"true train: {train_true} / {X_train.shape[0]}")
print(f"true test: {test_true} / {X_test.shape[0]}")

true train: 10269 / 11270
true test: 4699 / 7503


## RNN with pytorch

In [ ]:
x = torch.randint(0, 100, (3, 8))
print(x)
embedding = torch.nn.Embedding(100, 5) # vocab size = 100 so input to embedding layer < 100
print(embedding(x).shape) # [3, 8, 5] 
# 3x8 -> embedding -> 3x8x5 -> LSTM (with hidden size=3)-> 3x3

tensor([[ 5, 87, 41, 15, 71, 40, 83, 49],
        [82, 40, 57, 46, 30, 55,  5, 70],
        [80, 56, 90, 10, 11, 50, 28, 42]])
torch.Size([3, 8, 5])


In [ ]:
a = torch.randint(0, 5, (2, 3))
ebd = torch.nn.Embedding(10, 2)
print(a)
print(ebd(a))

tensor([[3, 2, 4],
        [2, 0, 1]])
tensor([[[ 0.1041,  0.1994],
         [ 0.2279,  0.6745],
         [-0.1467, -0.4252]],

        [[ 0.2279,  0.6745],
         [ 0.6440,  1.5220],
         [-0.2190,  0.3437]]], grad_fn=<EmbeddingBackward>)


In [ ]:
rnn = torch.nn.RNN(10, 20, 2) # (input_size, hidden_size, num_layer)
input = torch.randn(5, 3, 10) # (seq_len, batch, input_size) # input_size: kích thước 1 vector xt, seq_len: nof time step
h0 = torch.randn(2, 3, 20) # (num_layers * num_directions, batch, hidden_size)
# initial hidden state for each element in the batch. Defaults to zero if not provided

# output: (seq_len, batch, num_directions * hidden_size)
# hn: (num_layers * num_directions, batch, hidden_size)
output, hn = rnn(input, h0)

In [ ]:
length = [len(x) for x in X_train_count_idx]
length1 = [len(x) for x in X_test_count_idx]
np.mean(length) # 84.294942324756
np.mean(length1) # 82.27535652405705


#### prepare data for RNN naive approach

In [ ]:
# vectorize_tfidf.vocabulary_

In [ ]:
class InputUtils():
    def __init__(self, glove_file=""):
        self.word_vectors = self.load_glove_vectors()

    def load_glove_vectors(self, glove_file="/content/drive/My Drive/glove.6B.50d.txt"):
        """Load the glove word vectors"""
        glove_word_vectors = {}
        print(glove_file)
        with open(glove_file) as f:
            for line in f:
                split = line.split()
                glove_word_vectors[split[0]] = np.array([float(x) for x in split[1:]])
        return glove_word_vectors

    # @staticmethod
    def create_list_word_vector_from_sentence(self, sentence, sen_size): # todo: init result: zeros => set value=> faster than concatenate
        list_word = sentence.split(" ")
        matrix = np.zeros((sen_size, 50)) # padding = 0
        n = len(list_word)
        for i in range(min(n, 80)):
            matrix[i] = np.array(self.word_vectors.get(list_word[i], np.zeros((50,))).reshape(1, -1))

        assert matrix.shape[0] == 80, f"Output not match shape {matrix.shape}"
        return matrix
    
    # @staticmethod
    def create_input_from_corpus(self, list_sentence):
        n = len(list_sentence)
        output = np.zeros((n, 80, 50))
        for i in range(n):
            output[i] = self.create_list_word_vector_from_sentence(list_sentence[i], 80)
        assert output.shape == (len(list_sentence), 80, 50), f"Output not match shape {output.shape}"
        return output

In [ ]:
# list_sentence = ['hello my word', "how are you now"]
util = InputUtils("")
# output = ut.create_input_from_corpus(list_sentence)

/content/drive/My Drive/glove.6B.50d.txt


#### Test np reshape

In [ ]:
np.random.seed(68)
a = np.random.randint(0, 10, (3, 4, 5))
x, y, z = a.shape
b = np.zeros((y, x, z))

for i in range(a.shape[0]):
    b[:, i, :] = a[i]

print(a)
print('-------------------')
print(b)
print('-------------------')
print(a[0])
print('-------------------')
print(b[:, 0, :])

[[[2 7 4 0 8]
  [7 4 6 3 3]
  [8 5 1 9 8]
  [6 1 4 5 0]]

 [[7 3 5 4 7]
  [3 7 2 5 2]
  [9 8 0 9 0]
  [5 7 2 9 4]]

 [[4 2 2 7 7]
  [6 0 9 1 1]
  [0 4 3 4 7]
  [2 5 2 6 3]]]
-------------------
[[[2. 7. 4. 0. 8.]
  [7. 3. 5. 4. 7.]
  [4. 2. 2. 7. 7.]]

 [[7. 4. 6. 3. 3.]
  [3. 7. 2. 5. 2.]
  [6. 0. 9. 1. 1.]]

 [[8. 5. 1. 9. 8.]
  [9. 8. 0. 9. 0.]
  [0. 4. 3. 4. 7.]]

 [[6. 1. 4. 5. 0.]
  [5. 7. 2. 9. 4.]
  [2. 5. 2. 6. 3.]]]
-------------------
[[2 7 4 0 8]
 [7 4 6 3 3]
 [8 5 1 9 8]
 [6 1 4 5 0]]
-------------------
[[2. 7. 4. 0. 8.]
 [7. 4. 6. 3. 3.]
 [8. 5. 1. 9. 8.]
 [6. 1. 4. 5. 0.]]


In [ ]:
a

In [ ]:
start = time()
matrix_train = util.create_input_from_corpus(X_train)
end = time()
print(f"Prepare data for RNN done after {end - start}s")

Prepare data for RNN done after 3.184373378753662s


In [ ]:
start = time()
matrix_test = util.create_input_from_corpus(X_test)
end = time()
print(f"Prepare data for RNN done after {end - start}s")

Prepare data for RNN done after 2.4487249851226807s


array([[ 0.41037 ,  0.11342 ,  0.051524, ..., -0.36064 , -0.19616 ,
        -0.81066 ],
       [ 0.4786  ,  0.27493 , -1.2158  , ..., -0.93431 , -0.14269 ,
        -0.085625],
       [ 0.90512 ,  0.13008 ,  1.0917  , ...,  0.62759 ,  0.34694 ,
         0.46287 ],
       ...,
       [ 0.61183 , -0.22072 , -0.10898 , ..., -0.043688, -0.097922,
         0.16806 ],
       [ 1.0802  ,  0.085736,  0.28167 , ...,  0.062295,  0.16278 ,
         0.17376 ],
       [-0.66987 , -0.52013 ,  0.52627 , ...,  0.32978 ,  0.78675 ,
        -1.217   ]])

#### RNN model

In [ ]:
# class RNNModel(torch.nn.Module):
#     def __init__(self, input_size, output_size, hidden_size, num_layer, batch_size):
#         super(RNNModel, self).__init__()

#         self.hidden_size = hidden_size
#         self.num_layer = num_layer
#         self.batch_size = batch_size

#         self.rnn = torch.nn.RNN(input_size, hidden_size, num_layer, batch_first=True)
#         self.softmax1 = torch.nn.Softmax(dim=1)   
#         self.fc = torch.nn.Linear(hidden_size, output_size)
    
#     def forward(self, x):
#         hidden = torch.randn(self.num_layer, self.batch_size, self.hidden_size)
#         out, hidden = self.rnn(x, hidden)
#         out = out.contiguous().view(-1, self.hidden_size) # contiguous(): make a copy of out just ff
#         out = self.fc(out)
#         out = self.softmax1(out)
#         return out, hidden


In [ ]:
class RNNMd(torch.nn.Module):
    def __init__(self, input_size, hidden_size, num_layer, batch, output_size):
        super(RNNMd, self).__init__()
        self.num_layer = num_layer
        self.batch = batch
        self.hidden_size = hidden_size

        self.rnn = torch.nn.RNN(input_size, hidden_size, num_layer, batch_first=True)
        self.softmax1 = torch.nn.Softmax(dim=1)   
        self.fc = torch.nn.Linear(hidden_size, output_size)
        print("init model done!")
    def forward(self, x):
        """
        x: batch
        """
        # batch = x.size
        # batch_ = x.shape[1] # conflict name rs 
        # print("in forward")
        h0 = torch.zeros(self.num_layer, x.shape[1], self.hidden_size) # init
        # if torch.cuda.is_available():
        #     h0.cuda()
        # print("computing output done!")
        out, hn = self.rnn(x, h0)
        # checkout hn[-1] here instead of out[-1]
        out = hn[-1].contiguous().view(-1, self.hidden_size) # contiguous(): make a copy of out just ff, take last output only
        # out = self.fc(out) 
        out = self.softmax1(out)
        # print("done forward!")
        return out, hn

In [ ]:
# input_size, hidden_size, num_layer, batch, output_size = 50, 20, 1, 8, 20
# rnn = torch.nn.RNN(10, 20, 2) # (input_size, hidden_size, num_layer)
# input = torch.randn(5, 3, 10) # (seq_len, batch, input_size) # input_size: kích thước 1 vector xt, seq_len: nof time step
# h0 = torch.randn(2, 3, 20) # (num_layers * num_directions, batch, hidden_size)
# # initial hidden state for each element in the batch. Defaults to zero if not provided

# # output: (seq_len, batch, num_directions * hidden_size)
# # hn: (num_layers * num_directions, batch, hidden_size)
# output, hn = rnn(input, h0)

In [ ]:
# input_size, hidden_size, num_layer, batch, output_size = 50, 20, 1, 8, 20
# model = RNNMd(input_size, hidden_size, num_layer, batch, output_size)

# output, hn = model(torch.randn(80, batch, input_size))

In [ ]:
matrix_train = np.random.randn(100, 80, 50)
Y_train = np.random.randint(0, 99, (100,))

In [ ]:
from torch.utils.data import Dataset, DataLoader
class DataUtils(Dataset):
    def __init__(self, X, Y):
        # x, y, z = X.shape # not reshape like bro thought
        # X_reshape = np.zeros((y, x, z))
        # for i in range(X.shape[0]):
        #     X_reshape[:, i, :] = X[i]

        self.x = torch.from_numpy(X).float()
        self.y = torch.from_numpy(Y)
        self.length = self.x.shape[0]

    def __getitem__(self, index):    
        return self.x[index], self.y[index]

    def __len__(self):
        return self.length

dataset = DataUtils(matrix_train, Y_train)
trainloader = DataLoader(dataset=dataset, batch_size=128, shuffle=True)

In [ ]:
matrix_train.shape

(11270, 80, 50)

In [ ]:
torch.cuda.empty_cache()

input_size, hidden_size, num_layer, batch, output_size = 50, 40, 2, 128, 20
model = RNNMd(input_size, hidden_size, num_layer, batch, output_size)

if torch.cuda.is_available():
    pass
    # model.cuda()

print("done init model cuda")
criterion = torch.nn.CrossEntropyLoss()
lr = 0.005
optimizer = torch.optim.Adam(model.parameters(), lr)

epochs = 11
from time import time
t1 = time()
for epoch in range(epochs):
    for X, Y in trainloader:
        # x, y, z = X.shape # not reshape like bro thought
        # X_reshape = np.zeros((y, x, z))

        # for i in range(X.shape[0]):
        #     X_reshape[:, i, :] = X[i]

        X_reshape = torch.from_numpy(X_reshape).float()
        # if torch.cuda.is_available():
        #     # X = Variable(X.view(X.shape[1], X.shape[0], X.shape[2]).cuda())
        #     X = Variable(X_reshape)
        #     # Y = Variable(Y.cuda())
        #     Y = Variable(Y)
        # else:
        X = Variable(X)
        Y = Variable(Y)
        
        optimizer.zero_grad()
        output, hn = model(X)
        # print(f"shape of X: {X.shape}")
        # print(Y.shape)
        # print(X_reshape.shape)
        # print(output.shape)
        # break
        loss = criterion(output, Y)
        loss.backward()
        optimizer.step()
    if epoch % 2 == 0:
        # CUDA out of memory. ==>
        print(f"loss after {epoch} epochs: {loss}") # todo: test from here
        # pred1 = torch.argmax(model(torch.from_numpy(X_train[:1000]).view(X_train[:1000].shape[1], X_train[0], X_train[:1000].shape[2]).float().cuda()), axis=1)
        # s1 = sum(pred1 == torch.from_numpy(Y_train[:1000]).cuda())
        # print(f"true train: {s1}")

        # pred2 = torch.argmax(model(torch.from_numpy(X_test).view(X_test.shape[0], 1, X_test.shape[1]).float().cuda()), axis=1)
        # s2 = sum(pred2 == torch.from_numpy(Y_test_transform).cuda())
        # print(f"true test: {s2}")

print(f"training {epochs} epochs done after {time()-t1} s")

init model done!
done init model cuda
loss after 0 epochs: 3.673224687576294
loss after 2 epochs: 3.6643974781036377
loss after 4 epochs: 3.6786844730377197
loss after 6 epochs: 3.6676483154296875
loss after 8 epochs: 3.6648311614990234
loss after 10 epochs: 3.6620638370513916
training 11 epochs done after 67.64333820343018 s


In [ ]:
s = 0
for X, Y in trainloader:
    print(X.shape)
    print(Y.shape)
    x, y, z = X.shape # not reshape like bro thought
    X_reshape = np.zeros((y, x, z))
    for i in range(a.shape[0]):
        X_reshape[:, i, :] = X[i]
    print(X_reshape.shape)
    break
    X = Variable(X.view(X.shape[1], X.shape[0], X.shape[2]))
    Y = Variable(Y)
    print(X.shape, Y.shape)
    # print(model(X))
    break
    pred1 = torch.argmax(model(X), axis=1)
    s1 = sum(pred1 == torch.from_numpy(Y))
    s += s1
    print(f"true train: {s1}")

In [ ]:
s1 = 0
for X, Y in trainloader:
        if torch.cuda.is_available():
            # X = Variable(X.view(X.shape[1], X.shape[0], X.shape[2]).cuda())
            X = Variable(X.view(X.shape[1], X.shape[0], X.shape[2]))
            # Y = Variable(Y.cuda())
            Y = Variable(Y)
        else:
            X = Variable(X.shape[1], X.shape[0], X.shape[2])
            Y = Variable(Y)
        output, hn = model(X)
        pred1 = torch.argmax(output, axis=1)
        s1 += sum(pred1 == Y)
        # print(f"true train: {s1}")
s1

tensor(561)

In [ ]:
s1

tensor(1346)

In [ ]:
output.shape

torch.Size([1, 20])

In [ ]:
# !pip install -q --upgrade prompt-toolkit
!pip install -q --upgrade ipython
!pip install -q --upgrade ipykernel

*Another cause - if you're using PyTorch and assign your model to the GPU, but don't assign an internal tensor to the GPU (e.g. a hidden layer).*

*If you implement your own nn.Module, which includes some parameters inside. You should declare it as Parameters to let nn.Module.cuda() transfer the parameters into GPU memory.*

Keep in mind that only a limited number of optimizers support sparse gradients: currently it’s optim.SGD (CUDA and CPU), optim.SparseAdam (CUDA and CPU) and optim.Adagrad (CPU)

### RNN with embedding layer

In [ ]:
# nn.Embedding(num_embedding, embedding_dims,*): 
# A simple lookup table that stores embeddings of a fixed dictionary and size.
# x: matrix input 3*8
# y: embedding matrix 3*8*7
# if:
#     x[0, 4]==x[0, 5]==x[1, 4]
# then:
#     y[0, 4]==y[0, 5]==y[1, 4]
# same word => same embedding vector

# y[i, j] => embedding vector for word x[i, j]
# input: Input: (*)(∗) , LongTensor of arbitrary shape containing the indices to extract

In [5]:
def make_dict(corpus):
    coropa = {" ", "US0"} # " ": padding, US0: unseen word
    for sentence in corpus:
        for word in sentence.split():
            coropa.add(word)

    coropa = list(coropa)

    map_word = dict()
    for i, v in enumerate(coropa):
        map_word[v] = i
    return map_word

word2idx = make_dict(X_train) # 70739

In [6]:
# mean length: 80
def corpus2vec(corpus, word2idx, sen_size):
    def sen2vec(sentence):
        s = sentence.split()
        tmp = list(map(lambda x: word2idx.get(x, word2idx.get("US0")), s))
        n = len(tmp)
        if n < sen_size:
            tmp += [word2idx[" "]] * (sen_size-n)
        
        vector_sentence = np.array(tmp[:80])
        return vector_sentence
    
    n = len(corpus)
    sentence_matrix = np.zeros((n, sen_size))

    for i in range(n):
        sentence_matrix[i] = sen2vec(corpus[i])
    return sentence_matrix

sentence_matrix = corpus2vec(X_train, word2idx, 80)

In [11]:
class DataUtils(Dataset):
    def __init__(self, X, Y):
        self.X = X
        self.y = Y
        
    def __len__(self):
        return len(self.y)
    
    def __getitem__(self, idx):
        return torch.from_numpy(self.X[idx]).long(), self.y[idx]

dataset = DataUtils(sentence_matrix, Y_train)
trainloader = DataLoader(dataset=dataset, batch_size=256, shuffle=True)

In [12]:
test_matrix = corpus2vec(X_test, word2idx, 80)

testset = DataUtils(test_matrix, Y_test)
testloader = DataLoader(dataset=testset, batch_size=256, shuffle=True)

In [21]:
class RNNEbd(torch.nn.Module):
    def __init__(self, vocab_size, ebd_dim, num_layers, hidden_size, output_size):
        super(RNNEbd, self).__init__()
        self.embeddings = torch.nn.Embedding(vocab_size, ebd_dim) # add pad before
        self.lstm = torch.nn.LSTM(ebd_dim, hidden_size, num_layers, batch_first=True)
        self.dropout = torch.nn.Dropout(0.4)
        # change
        self.linear = torch.nn.Linear(hidden_size, output_size)
        # self.linear2 = torch.nn.Linear(20, output_size)
        self.softmax = torch.nn.Softmax(dim=1)
    def forward(self, x):
        output = self.embeddings(x)
        output = self.dropout(output)
        # output, hn = self.rnn(output)
        lstm_out, (ht, ct) = self.lstm(output)
        output = self.linear(ht[-1])
        # output = self.linear2(output)
        output = self.softmax(output)
        return output

In [22]:
model = RNNEbd(len(word2idx), 300, 1, 50, 20)
criterion = torch.nn.CrossEntropyLoss()
lr = 0.005
optimizer = torch.optim.Adam(model.parameters(), lr)

epochs = 101
from time import time
t1 = time()
for epoch in range(epochs):
    for X, Y in trainloader:
        X = X.long()

        optimizer.zero_grad()
        output = model(X)
        loss = criterion(output, Y)
        loss.backward()
        optimizer.step()
    if epoch % 5 == 0:
        # CUDA out of memory. ==>
        print(f"loss after {epoch} epochs: {loss}") # todo: test from here
        s = 0
        for X, Y in trainloader:
            X = X.long()
            output = model(X)
            pred = torch.argmax(output, axis=1)
            tmp = torch.sum(pred==Y)
            s += tmp
        print(s)
        s = 0
        for X, Y in testloader:
            X = X.long()
            output = model(X)
            pred = torch.argmax(output, axis=1)
            tmp = torch.sum(pred==Y)
            s += tmp
        print(s)

print(f"training {epochs} epochs done after {time()-t1} s")

loss after 0 epochs: 2.997466802597046
tensor(1265)
tensor(580)
loss after 5 epochs: 2.585172653198242
tensor(3804)
tensor(1590)
loss after 10 epochs: 2.8502063751220703
tensor(5622)
tensor(2356)
loss after 15 epochs: 2.8906688690185547
tensor(7022)
tensor(2959)
loss after 20 epochs: 2.4569685459136963
tensor(8200)
tensor(3514)
loss after 25 epochs: 2.4102141857147217
tensor(8872)
tensor(3983)
loss after 30 epochs: 2.2513835430145264
tensor(9220)
tensor(4134)
loss after 35 epochs: 2.568661689758301
tensor(9725)
tensor(4286)
loss after 40 epochs: 2.269740343093872
tensor(9768)
tensor(4336)
loss after 45 epochs: 2.2450950145721436
tensor(10058)
tensor(4493)
loss after 50 epochs: 2.0784685611724854
tensor(10246)
tensor(4684)
loss after 55 epochs: 2.1063005924224854
tensor(10367)
tensor(4620)
loss after 60 epochs: 2.241914749145508
tensor(10470)
tensor(4709)
loss after 65 epochs: 2.0905604362487793
tensor(10517)
tensor(4772)
loss after 70 epochs: 2.2492287158966064
tensor(10557)
tensor(484

In [ ]:
# loss after 0 epochs: 2.982945442199707
# tensor(1498)
# tensor(665)
# loss after 5 epochs: 2.8098628520965576
# tensor(4826)
# tensor(1834)
# loss after 10 epochs: 2.4296891689300537
# tensor(6983)
# tensor(2891)
# loss after 15 epochs: 2.578169584274292
# tensor(8144)
# tensor(3437)
# loss after 20 epochs: 2.37660813331604
# tensor(8720)
# tensor(3770)
# loss after 25 epochs: 2.4084534645080566
# tensor(9064)
# tensor(3957)
# loss after 30 epochs: 2.1120564937591553
# tensor(9524)
# tensor(4178)
# loss after 35 epochs: 2.0857508182525635
# tensor(9887)
# tensor(4285)
# loss after 40 epochs: 2.1238152980804443
# tensor(10193)
# tensor(4438)
# loss after 45 epochs: 2.1881587505340576
# tensor(10356)
# tensor(4546)
# loss after 50 epochs: 2.0784521102905273
# tensor(10489)
# tensor(4578)
# loss after 55 epochs: 2.07915997505188
# tensor(10564)
# tensor(4662)
# loss after 60 epochs: 2.0783541202545166
# tensor(10623)
# tensor(4745)
# loss after 65 epochs: 2.0781590938568115
# tensor(10652)
# tensor(4779)
# loss after 70 epochs: 2.078335762023926
# tensor(10670)
# tensor(4802)
# loss after 75 epochs: 2.078561544418335
# tensor(10694)
# tensor(4849)
# loss after 80 epochs: 2.0781846046447754
# tensor(10706)
# tensor(4849)
# loss after 85 epochs: 2.0872957706451416
# tensor(10725)
# tensor(4892)
# loss after 90 epochs: 2.0781571865081787
# tensor(10734)
# tensor(4915)
# loss after 95 epochs: 2.1022636890411377
# tensor(10727)
# tensor(4881)
# loss after 100 epochs: 2.244936227798462
# tensor(10762)
# tensor(4856)
# training 101 epochs done after 2350.489052772522 s

In [ ]:
s = 0
for X, Y in testloader:
    X = X.long()
    output = model(X)
    pred = torch.argmax(output, axis=1)
    tmp = torch.sum(pred==Y)
    s += tmp
print(s)

tensor(4169)


In [ ]:
Y_test.shape

(7503,)